mudpuppy/src/tui/splitview.rs

The `mudbuffer.rs` TUI code was filtering gagged MUD items but the splitview was not. In the future we can consider (for both, or separately) exposing a config to display gagged items (perhaps grayed out) as a debug aide.

tui: hide gagged items in history splitview

---

README.md
mudpuppy/python/cmd_trigger.py
mudpuppy/python/mudpuppy.py
mudpuppy/src/client/mod.rs
mudpuppy/src/model.rs
mudpuppy/src/tui/mudbuffer.rs
mudpuppy/src/tui/splitview.rs

It's now possible to indicate in a trigger config if the pattern should only match lines detected as a prompt. Writing this kind of trigger is an alternative to writing prompt event handlers and allows for gagging the prompt lines and more complex pattern matching.
For a decorator trigger that only matches on prompt lines, add `prompt=True`, e.g:
```python
@trigger(name="Gag login prompts", prompt=True, gag=True, pattern=r"(?:Enter your username: )|(?:Password: )")
async def gag_prompts(_session_id: SessionId, _trigger_id: TriggerId, line: str, _groups: Any):
logging.debug(f"\nI just gagged this prompt:\n{line}\n")
```
For a trigger added in-client that only matches on prompt lines, add `--prompt`, e.g:
```
/trigger add --name='Gag username prompt' --prompt --gag --pattern='Enter your …
```

support triggers on prompt lines

---

README.md
mudpuppy/python/mudpuppy.py
python-examples/user_test.py

It's now possible to specify a list for the `mud_name` argument of the various decorators (`@trigger`, `@alias`, `@on_event`, etc).
The registered handler will be activated for any MUD that matches one of the provided `mud_name`s.
E.g. an alias that's defined for two MUDs:
```python
@alias(mud_name=["Dune (TLS)", "Threshold"], pattern="^eepy$", name="Eepy", expansion="say I'm eepy")
async def eepy(session_id: SessionId, _alias_id: AliasId, _line: str, _groups):
pass
```
Resolves https://github.com/mudpuppy-rs/mudpuppy/issues/24

support multiple `mud_name`s in decorators

---

README.md
user-guide/src/SUMMARY.md
user-guide/src/chapter_1.md
user-guide/src/cli.md
user-guide/src/commands.md
user-guide/src/config.md
user-guide/src/introduction.md
user-guide/src/logging.md
user-guide/src/scripting/README.md
user-guide/src/scripting/aliases.md
user-guide/src/scripting/custom_commands.md
user-guide/src/scripting/output.md
user-guide/src/scripting/prompts.md
user-guide/src/scripting/timers.md
user-guide/src/scripting/triggers.md

Some new content (e.g. on `OutputItems`) is added along the way. There's still a lot more polish required but having the content out of the `README` and in a more structured format (that's easy to view online!) gives us a good place to start.

docs: migrate content from README -> book

---

mudpuppy/python/history.py
mudpuppy/src/python.rs
user-guide/src/scripting/output.md

This branch adds a new `mudpuppy_core.print()` fn that has a Python fn signature matching the `print()` built-in.
Crucially, the `mudpuppy_core` version doesn't write to stdout and instead converts each line of what _would_ have been printed to stdout into debug `OutputItem`'s appended to the currently active sessions's output buffer.
As a result it's now safe to use from `/py` with appropriate quoting:
```
/py print(\"This is a test!\\nDebug debug debug!\")
```
Scripts can also invoke `print("...")` with normal Python syntax, but care should be taken to make sure there's an active session. E.g. Python code that runs when the client starts before any sessions are started that uses `print()` will not display any output. Prefer `logging` for that use-case.
Resolves …

python: print() builtin -> mudpuppy_core.print()

---

mudpuppy/src/tui/mudbuffer.rs

For some reason the `\t` character in MUD output causes weird glitchy rendering in the mudbuffer after it's run through the `ansi-to-tui` crate's conversion to `ratatui::Text`.
We can work around this issue for now by replacing tabs with four literal spaces. It Works :tm: Ship it.
Resolves https://github.com/mudpuppy-rs/mudpuppy/issues/25

mudbuffer: replace \t prior to rendering

---

Cargo.lock
Cargo.toml
flake.nix
mudpuppy/Cargo.toml
mudpuppy/src/client/input.rs
mudpuppy/src/client/mod.rs
mudpuppy/src/main.rs
mudpuppy/src/model.rs
mudpuppy/src/python.rs
mudpuppy/src/tui/layout.rs

See the [migration guide](https://pyo3.rs/v0.22.0/migration.html) for more information.
We're presently using the `py-clones` opt-in feature to keep the pre-existing behaviour of cloneable pyclasses. Unfortunately these now panic at runtime if the GIL isn't held (ugh). I've done my best to catch these potential panic sites but no doubt missed one somewhere. In the future we should consider dropping this feature to avoid the footgun and find alternatives where required.
Another small wrinkle: the pyo3 <-> tokio async bridge library has been updated for PyO3 (now under a new name, `pyo3-async-runtimes`) but that support hasn't been released yet. Since we don't publish this app on crates.io it's not a big deal to take a cargo patch to use the unreleased code while we wait.
This brings …

update pyo3 0.21 -> 0.22

---

.github/dependabot.yml
Cargo.lock

* deps: console-subscriber 0.4.0 -> 0.4.1
* deps: tonic 0.12.1 -> 0.12.3 - Bumps the transitive tonic dep to avoid a build breakage from console-subscriber update.
* ci: reduce dependabot cargo update frequency - I generally only have time to fiddle w/ Mudpuppy on weekends.
Replaces https://github.com/mudpuppy-rs/mudpuppy/pull/51

semver compat dep updates, dependabot frequency tweak

---

README.md
mudpuppy/src/config.rs
mudpuppy/src/model.rs
mudpuppy/src/python.rs
python-stubs/mudpuppy_core.pyi

Phew! Lots to document. This commit adds a first rough pass of API documentation & stubs for the `mudpuppy_core` module and its types, functions, and member vars.

docs: first pass of `mudpuppy_core` API docs

---

Cargo.lock
Cargo.toml
mudpuppy/src/app.rs
mudpuppy/src/tui/buffer.rs
mudpuppy/src/tui/input.rs

Jumping from ratatui 0.27 to [0.29](https://github.com/ratatui/ratatui/releases/tag/v0.29.0). This was relatively painless, and only required fixing a couple breaks/deprecation warns. Likely there are some other places that could be cleaned up using new features from 0.27+ but for now let's just get everything working as-is. The `ansi-to-tui` release is updated to match `ratatui` versions.
Crossterm gets bumped alongside to match Ratatui's req. We can't use the Ratatui re-export because we want to activate some features on crossterm ourselves (event-stream, bracketed-paste, etc).
Lastly, `notify` is updated to [7.0.0](https://github.com/notify-rs/notify/releases/tag/notify-7.0.0) - no changes req'd.

update ratatui/crossterm/notify to latest

---

flake.nix
mudpuppy/python/cmd_alias.py
mudpuppy/python/cmd_misc.py
mudpuppy/python/cmd_py.py
mudpuppy/python/cmd_status.py
mudpuppy/python/cmd_timer.py
mudpuppy/python/cmd_trigger.py
mudpuppy/python/commands.py
mudpuppy/python/history.py
mudpuppy/python/layout.py
mudpuppy/python/mudpuppy.py
mudpuppy/python/telnet_charset.py
mudpuppy/python/telnet_naws.py
mudpuppy/src/python.rs
mudpuppy/src/tui/reflow.rs
pyproject.toml
python-examples/custom_layout.py
python-examples/gmcp_channels.py
python-examples/gmcp_status.py
python-examples/user_test.py
python-stubs/commands.pyi
python-stubs/layout.pyi
python-stubs/mudpuppy.pyi
python-stubs/mudpuppy_core.pyi

* Ratatui vendored reflow code update
* ruff-format pre-commit hook
* pyright pre-commit hook
* a lot more stubs/API documentation
As of this point all of the bundled .py code (`mudpuppy/python/*.py` and `python-examples/*.py`) passes static typechecking with `pyright` and the `.pyi` stubs.

stubs, stubs, stubs

---

Cargo.lock
Cargo.toml
flake.nix
python-stubs/mudpuppy.pyi
python-stubs/mudpuppy_core.pyi

* `pyo3-async-runtimes` cut a [0.22 release](https://github.com/PyO3/pyo3-async-runtimes/releases/tag/v0.22.0) so we can drop the cargo patch
* I was using Python `assert` and type checking wrong in some stub example code. Tidy that up.

remove pyo3-async-runtimes cargo patch, tidy up stub assertions

---

mudpuppy/python/cmd_py.py
python-stubs/commands.pyi

* Escape `"` and `'` automatically, so you can write `/py "foo"` instead of `/py \"foo\"`.
* Don't display `None` results.
* Automatically `await` any awaitable results.
* Use `exec()` for things that aren't an `eval()`-able expression. This allows defining functions, setting variables, importing modules, and so on.
* Persist `globals()` between `/py` calls. This means you can do things like `/py import random` and then `/py random.randint(10, 20)` or `/py foo = "hello"` followed by `/py foo`.
Lots of room for improvement left:
* importing more stuff by default?
* offering some helper fns?
* some manner of multi-line input ala `python` REPL when you `def foo(): `... and then enter each line at a time?

python: improve /py command ergonomics

---

mudpuppy/python/mudpuppy.py
python-stubs/mudpuppy_core.pyi

The `mudpuppy` Python module is a good place to set up a custom Python `warnings.showwarning` handler to redirect warnings to `logging` and the active session's output buffer. The default behaviour is to print the warning to stdout, but since we're drawing a TUI there it will corrupt the interface.
This is particularly important because common mistakes like forgetting to await a coroutine will provoke this warning path. We both need to avoid corrupting the UI in that case, but also surface the error to the user.
Along the way, fix the name of the `mudpuppy_core.MudpuppyCore.active_session_id()` stub.

python: catch warnings to avoid stdout corruption

---

mudpuppy/src/client/input.rs
mudpuppy/src/client/mod.rs
mudpuppy/src/config.rs
mudpuppy/src/model.rs
mudpuppy/src/python.rs
python-stubs/mudpuppy_core.pyi
user-guide/src/SUMMARY.md
user-guide/src/input.md

Couple small changes from last weekend I want to clear from my WIP branch:
A plural version of `MudPuppyCore.send_line()` for convenience. Should have had this from the start :-P
The command splitter is specified in the MUD config and defaults to ';;'. Splitting is performed in two places:
* When processing human input from an enter keypress (notably, before aliases are evaluated). This allows input like 'say hi;;/py True;;say whatever" where slash commands from aliases can be used.
* When processing scripted input from `send_line()` or `send_lines()` - in this case alias expansion isn't performed (and getting that to happen is architecturally tricky...) but this is an existing limitation of those APIs.
I'm a little unhappy with the duplication & limitations uncovered by playing with this …

send_lines(), command splitting support

---

pdoc-templates/syntax-highlighting.css
pdoc-templates/theme.css

makes the light theme the default again and auto detect os/browser settings for dark mode.
I was hoping to also add a button to manually select themes but without changing the upstream templates I think this is 10% of the effort for 90% of the benefit.

Auto detect theme preferences for api docs

---

python-stubs/mudpuppy_core.pyi

Fix the name of the session id argument in new_alias and new_trigger

Update python stubs to match argument names

---

Cargo.lock
Cargo.toml
README.md
mudpuppy/python/cmd_alias.py
mudpuppy/python/cmd_timer.py
mudpuppy/python/cmd_trigger.py
mudpuppy/python/history.py
mudpuppy/python/mudpuppy.py
mudpuppy/src/client/mod.rs
mudpuppy/src/error.rs
mudpuppy/src/python.rs
mudpuppy/src/tui/layout.rs
mudpuppy/src/tui/mudbuffer.rs

Forgot to give the newly `Optional` field a default value of `None`, preventing it from being truly optional. Oops!
The Tokio timer implementation's `tick()` function always yields immediately on the first poll. This is counter to user expectation
because it means when you add a timer with a duration, it will run immediately, not after the duration expires. Work-around this with a quick'n'cheap bool check to skip the first iteration without affecting the tick count.
Does what it says on the tin. Better output formatting still needed.
This is an important mechanic and is required (for example) when reading a man page on an LP MUD that mimics a "more" utility. It worked previously but regressed when the cmd separator feature landed.
Now that we can send empty lines again, don't bother …

misc saturday morning fixes/updates

---

Cargo.lock
flake.lock

Notably this picks up an upstream fix that prevents an eval failure about missing pass-through targets on latest nixpkgs when using this repo as a flake input.
Also tacked on a PyO3 update to address GHSA-vxcf-c7mx-pg53.

flake: take latest rust-overlay

---

flake.lock
mudpuppy/src/net/telnet/codec.rs
mudpuppy/src/python.rs

* update flake inputs - notably this picks up the latest nightly
* address nightly clippy findings - fix one, ignore one.

small touchups to knock the dust off main

---

mudpuppy/src/app.rs
mudpuppy/src/config.rs

A larger overhaul is needed but let's stop the bleeding first:
* always treat tabkind used for the key binding mode as lowercase.
* if custom keybindings are present in the config, merge with the defaults, preferring the user binding where there is a conflict.
* print the full set of resolved keybindings afterwards at the trace log level. It's spammy, but that's what trace is for. Use a higher log level if you don't want spam!
Updates https://github.com/mudpuppy-rs/mudpuppy/issues/33

quick keybinding fixes

---

mudpuppy/src/app.rs
mudpuppy/src/client/input.rs
mudpuppy/src/client/mod.rs

Previously I tried to fix a Windows-specific duplicated key press glitch by filtering out the non-press events in the input TUI code. In practice this needs to be done earlier so it applies globally: for all widgets, and the Python events produced for key presses.
This fixes glitchy behaviour on Windows where (for example) pressing F5 to hide a custom layout UI element would flicker it, or pressing CTRL-N/CTRL-P to change tabs would skip multiple tabs.

app: filter non-press key events earlier

---

python-examples/gmcp_channels.py

Some system locales are not utf-8 friendly, so we can avoid exceptions when logging gmcp chat that contains unicode characters by explictly setting the encoding for the log file.

Explicitly set file encoding in gmcp_channels.py example

---

mudpuppy/src/python.rs
python-stubs/mudpuppy_core.pyi

Update some python stubs to use correct argument name for session_id and change timer functions id arguments to the more descriptive timer_id name.

Fix argument names

---

mudpuppy/python/history.py
mudpuppy/src/client/input.rs
mudpuppy/src/client/mod.rs
mudpuppy/src/python.rs
mudpuppy/src/tui/input.rs
mudpuppy/src/tui/mudlist.rs
mudpuppy/src/tui/session.rs
python-examples/spellcheck.py
python-stubs/mudpuppy_core.pyi

This means moving from holding `Input` to `Py<Input>` in the `Client` struct, and acquiring the GIL for use from Rust. This was my original intent (`Input` is already a pyclass and has stubs!) and it simplifies the `mudpuppy_core` API from the Python side. The `history.py` built-in module shows the improvement nicely. 
Adds new `Input` APIs for decorating the to-be-sent queued input text with ANSI colour:
* `add_markup(idx, str)`
* `remove_markup(idx)`
* `clear_markup()`
* `markup() -> dict[int, str]`
* `decorated_value() -> str`
The markup text is interleaved when displaying the text in the TUI (or when `decorated_value()` is used), but it is kept separate from the data transmitted to the MUD.
An example is provided that uses a key event handler to provide highlighting of known slash …

rework Input API, add markup, spellcheck example

---

.config/config.toml
flake.lock
mudpuppy/src/app.rs
mudpuppy/src/client/mod.rs
mudpuppy/src/config/config_file.rs
mudpuppy/src/model.rs
mudpuppy/src/python.rs
mudpuppy/src/tui/session.rs
python-stubs/mudpuppy_core.pyi
user-guide/src/SUMMARY.md
user-guide/src/config/README.md
user-guide/src/config/mouse.md
user-guide/src/scripting/editing.md

Some quick changes from some afternoon hacking:
* I tweaked and expanded the user guide content for IDE setup started in https://github.com/mudpuppy-rs/mudpuppy/pull/95 - it now covers PyCharm and Pyright in addition to VS Code.
* I bumped the flake inputs, mostly to pick up a fresher nightly rust.
* I added optional mouse support, controlled by a global config bool, `mouse_enabled`, that defaults to off. Mouse support breaks the normal terminal copy/paste interaction so I think it's something best turned on by someone that knows what they want and the side effects (which are described in a new user guide page). Because of the way terminal capability registration is handled presently, changing this option requires a client restart. Might be able to fix that up later but it seemed …

user guide IDE doc expansion, initial mouse support & mouse scrolling.

---

.config/config.toml
.github/workflows/rust.yml
.gitignore
Cargo.lock
Cargo.toml
mudpuppy/Cargo.toml
mudpuppy/src/app.rs
mudpuppy/src/client/mod.rs
mudpuppy/src/config/config_file.rs
mudpuppy/src/model.rs
mudpuppy/src/python.rs
mudpuppy/src/tui/annotation.rs
mudpuppy/src/tui/button.rs
mudpuppy/src/tui/mod.rs
mudpuppy/src/tui/session.rs
python-examples/custom_layout.py
python-examples/spellcheck.py
python-stubs/mudpuppy_core.pyi
user-guide/src/config/mouse.md

* Properly disable mouse capture on exit. This prevents weirdness in the terminal after exiting when `mouse_enabled` was true.
* Allow changing mouse mode without a restart. This removes the previous limitation that required a restart of the client for the change to take effect. A new `ToggleMouseMode` shortcut is added, and bound to F8 by default, to toggle mouse mode from within the client. The user manual is updated to remove the mentions of needing a restart.
* Add button widgets, scriptable with Python. These are missing styling, but function in the most basic prototype sense. You can create buttons from Python, and have an async callback invoked when they're clicked in mouse mode. The `custom_layout.py` example is updated to add navigation buttons for moving around in-game. For now …

misc mouse improvements, further prototyping

---

mudpuppy/src/python.rs
mudpuppy/src/tui/annotation.rs
python-examples/spellcheck.py

* don't bother with enabled state. Not very useful, better to redraw no content.
* clear annotation on input sent events.
* tidy some spellcheck example code.

minor iterations on spellcheck/annotations

---

flake.lock
mudpuppy/src/idmap.rs
mudpuppy/src/tui/buffer.rs

Pretty gross hack, but it's sufficient to prevent buffer corruption when working through the entire list of emoji DuneMUD recognizes.
Some more complex emoji will lose indicators like skin tone, but until there's an upstream fix this is better than corrupting the TUI and leaving half-drawn stuff all over the place.
Resolves https://github.com/mudpuppy-rs/mudpuppy/issues/80 (_TODO: update that issue with some breadcrumbs to the upstream work to be done_).

buffer: workaround ratatui complex emoji buffer corruption

---

Cargo.lock
Cargo.toml

Resolves [RUSTSEC-2025-0020](https://rustsec.org/advisories/RUSTSEC-2025-0020.html), a PyO3 vuln in API surface we're not using.

Cargo: bump pyo3 ecosystem crates
